# Generated by Django 5.0.1 on 2024-02-07 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "avatar",
                    models.FileField(
                        default=None, max_length=255, null=True, upload_to="avatars"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "avatar",
                    models.FileField(
                        default=None, max_length=255, null=True, upload_to="avatars"
                    ),
                ),
            ],
        ),
    ]
